path:
  image_folder: ./data/graph_image
  output_folder: ./checkpoints

agent:
  model: qwen2.5-vl-32b-instruct 
  temperature: 0.1
  api_key: YOUR_API_KEY
  base_url: YOUR_BASE_URL
  system_prompt: |-
    You are a helpful assistant.

    # Tools

    You may call one or more functions to assist with the user query.

    You are provided with function signatures within <tools></tools> XML tags:
    <tools>
    {{"type": "function", "function": {{"name_for_human": "mobile_use", "name": "mobile_use", "description": "Use a touchscreen to interact with a mobile device, and take screenshots.
    * This is an interface to a mobile device with touchscreen. You can perform actions like clicking, typing, swiping, etc.
    * You must open app with action open[app] in Chinese name directly, do not click the app icon to open it. 
    * Some applications may take time to start or process actions, so you may need to wait and take successive screenshots to see the results of your actions.
    * The screen's resolution is {width}x{height}.
    * Make sure to click any buttons, links, icons, etc with the cursor tip in the center of the element. Don't click boxes on their edges unless asked.", "parameters": {{"properties": {{"action": {{"description": "The action to perform. The available actions are:
    * `click`: Click the point on the screen with coordinate (x, y).
    * `long_press`: Press the point on the screen with coordinate (x, y) for specified seconds.
    * `swipe`: Swipe from the starting point with coordinate (x, y) to the end point with coordinates2 (x2, y2).
    * `type`: Input the specified text into the activated input box.
    * `system_button`: Press the system button.
    * `open`: You must open app on the device with action open[app] directly, do not click the app icon to open it.
    * `wait`: Wait specified seconds for the change to happen.
    * `terminate`: Terminate the current task and report its completion status.", "enum": ["click", "long_press", "swipe", "type", "system_button", "open", "wait", "terminate"], "type": "string"}}, "coordinate": {{"description": "(x, y): The x (pixels from the left edge) and y (pixels from the top edge) coordinates to move the mouse to. Required only by `action=click`, `action=long_press`, and `action=swipe`.", "type": "array"}}, "coordinate2": {{"description": "(x, y): The x (pixels from the left edge) and y (pixels from the top edge) coordinates to move the mouse to. Required only by `action=swipe`.", "type": "array"}}, "text": {{"description": "Required only by `action=key`, `action=type`, `action=answer`, and `action=open`.", "type": "string"}}, "time": {{"description": "The seconds to wait. Required only by `action=long_press` and `action=wait`.", "type": "number"}}, "button": {{"description": "Back means returning to the previous interface, Home means returning to the desktop, Menu means opening the application background menu, and Enter means pressing the enter. Required only by `action=system_button`", "enum": ["Back", "Home"], "type": "string"}}, "status": {{"description": "The status of the task. Required only by `action=terminate`.", "type": "string", "enum": ["success", "failure"]}}}}, "required": ["action"], "type": "object"}}, "args_format": "Format the arguments as a JSON object."}}}}
    </tools>

    For each function call, return a json object with function name and arguments within <action></action> XML tags, and summarize your action description in <thinking></thinking> tags:
    <action>
    {{"name": mobile_use, "arguments": <args-json-object>}}
    </action>
    <thinking>
    [action description]
    </thinking>
  
graph:
  graph_file: ./data/graph.json
  root_node: update_by_hand_Screenshot_2025-09-08-12-52-48-00_b783bf344239542886fee7b48fa4b892.jpg

tasks:
  tasks_file: ./data/tasks.json
  max_steps: 40



